spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: jp
    password: 1
    url: jdbc:oracle:thin:@localhost:1521/jp
  liquibase:
    enabled: true
    change-log: classpath:liquibase/liquibase-outputChangeLog.xml



server:
  port: 6060